### PR TITLE
Local files based sync

### LINKED ISSUE #99: Improve "Document loading error" screen
As I'm migrating to a UI router, I realize I didn't implement document loading error screen to make it umm... usable. 
Screen Shot 2022-04-05 at 5 07 16 PM

In reality the calendar / dropdown should possibly be disabled -- you can't do much from the screen if the document id is invalid. The lack of error is a bit puzzling. 

- [ ] Ensure "back" behavior works
- [ ] Add a "Document with id `?` failed to load. Error is: ... 
- [ ] Disable meaningless date and journal dropdown

### PR DESCRIPTION
**Pull request by cloverich**
Re-works the database back to a cache over files - the app now layers over a directory of markdown files where the files are the source of truth. This is how the app was originally envisioned / previously implemented (see #61). 

This requires the directory to adhere to the following structure:

```sh
/_attachments # <-- all images, file links, etc, go here
/my_journal_1
  016e4a96-ff00-763d-83c3-2e6c9a7a287b.md
  016e4a97-4d20-7e0d-b2dd-8bdaa65ed981.md
/my_journal_2
  # ...
```

Screenshot of my notes directory:
Screenshot 2024-09-23 at 8 27 31 AM

Note title, tags, and create / updated timestamps are stored in front matter:

```yaml
---
title: Re-importing exported Chronicles directory
tags: thesixthprototype
createdAt: 2024-09-17T01:45:39.880Z
updatedAt: 2024-09-17T20:41:46.532Z
---
```

The filename serves as the unique identifier for the document; id format will be revisted in #248 , support for additional front matter (at least, preserving its existence) will be reviewed in #127 

I have a lot of mixed feelings about the work in this PR. It makes everything about the application more complicated. It hopefully sets up better for default sync (via iCloud, whatever), but there remains a few more tasks to make it a bit more robust. It will likely have some issues, but should be safer than syncing the database (What I was doing previously -- I wasn't using the app daily until recently). At this point going to roll with it a while and make some more incremental changes, as documented in #247 

- Closes (obviates) #52 
- Closes (obviates) #41
- Closes (obviates) #131 
- Closes #99 (navigates back to /documents when file not found)

### CODE REVIEW

File: src/preload/client/documents.ts [hunk 1]
```diff
@@ -1,14 +1,15 @@
...
+import { IFilesClient } from "./files";
 
 export interface GetDocumentResponse {
   id: string;
   createdAt: string;
   updatedAt: string;
   title?: string;
   content: string;
-  journalId: string;
+  journal: string;
```
Comment (cloverich) [inline src/preload/client/documents.ts:12]: Re-worked the journal references from id to name, to support reconciling synced journal names with what's in the cache. Probably this was a mistake, but I tied up the change too tightly to all the other work; may re-visit this in the near future.

File: src/preload/client/journals.ts [hunk 2]
```diff
@@ -1,83 +1,125 @@
...
-        name,
-        id: journal.id,
+        name: journal.name,
+        newName,
         updatedAt: new Date().toISOString(),
       });
 
+    // todo: dumb; revert to having documents reference id instead of name
+    this.db
+      .prepare("update documents set journal = :newName where journal = :name")
```
Comment (cloverich) [inline src/preload/client/journals.ts:81]: Example of where changing the reference to be by name results in extra work; obviously dumb design here. But works for now....

File: src/preload/importer/importChronicles.ts
Comment (cloverich) [inline src/preload/importer/importChronicles.ts:1]: This importer is a legacy of the prior file-based format, which IIRC was something like:

```sh
/my_journal
  2024/
    /04
      /01
# etc
```

Because I did not use front-matter, and because the `ctime` / `mtime` could be changed by bulk file moves / zip / cloud sync, I relied on the filename for the date of the note. I think it makes sense to leave this until I'm satisfied with the final format of Chronicles data, and especially until I introduce markdown importers.
