### PR TITLE
Fix search persistence

### LINKED ISSUE #150: Back button doesn't maintain `in:` state
I can't believe this _already_ broke, lol. Desperately need #117

### PR DESCRIPTION
**Pull request by cloverich**
Fix search persistence when navigating in and out of notes, if search was not initiated by pagination (i.e. sidebar). Caused by setSearch not updating the URL. Fixing that revealed a loop, and required refactoring to use the route tree to control which components have access to the search store

Notably, in #150 I called this a bug and asked how it broke. It was actually never implemented -- search persistence was only partially implemented. This finishes the implementation, and also improves the design in that components requiring the persistent store all receive it from a shared ancestor (route); removes the need for a couple hacks. 

Closes #150

### CODE REVIEW

File: src/views/documents/SearchProvider.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+import { LayoutDummy } from "../../layout";
+
+export function SearchProvider(props: any) {
+  const jstore = useContext(JournalsStoreContext);
+  const client = useClient();
+  const [params, setParams] = useSearchParams();
+  const [searchStore, setSearchStore] = useState<null | SearchStore>(null);
+
+  // This is more like an effect. This smells. Maybe just roll this all up into
+  // a hook.
```
Comment (cloverich) [inline src/views/documents/SearchProvider.tsx:16]: Probably should remove this (copied from container); this component is sufficiently special purpose.
